### ISSUE TITLE
ValueError: Cannot find global function tir.schedule.NormalizePrimFunc

### ISSUE THREAD

**Issue by XA23i** [microsoft/BitBLAS#109]

**Comment by LeiWang1999** [comment]
Hi @XA23i , would you mind provide the scripts to reproduce this issue?

**Comment by XA23i** [comment]
after i install bitblas, i also install apache-tvm. then i run ' python -c "import bitblas; print(bitblas.__version__)"  '.
this cause this error.
btw: i go through the internet and find tvm.gpu().exist() is false.

**Comment by LeiWang1999** [comment]
Hello @XA23i, there's no need to manually install apache-tvm; bitblas includes a customized version of tvm that will automatically be installed when you install from PyPI.

**Comment by XA23i** [comment]
ohh, if it can run if i do not install apache-tvm. but there is another error:
![image](https://github.com/user-attachments/assets/12018d04-8d5d-49c3-a49f-a34e831c8d04)

**Comment by LeiWang1999** [comment]
When you install bitblas using `pip install bitblas`, it's important not to place your workspace in the BitBLAS project's root directory. Doing so will lead the Python interpreter to use the local bitblas directory rather than the installed package.

If you want to build bitblas from source, `install.sh` should be executed under the root to install, the scripts will automatically build tvm.

**Comment by XA23i** [comment]
Thank you very much, it works~

**Comment by LeiWang1999** [comment]
@XA23i  welcome! Glad to hear it worked ：）
